# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: yiisoftware/yii2-php:7.1-apache #circleci/php:7.1-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: /var/www/html/

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: pwd
      - run: ls -al
      - run: rm -R vendor
      - run: composer -V
      - run: composer clear-cache

      - run: composer install --ignore-platform-reqs --no-scripts
      - run: composer require guzzlehttp/guzzle
      - run: composer show --installed

      - run: ls -al vendor/symfony/console/Formatter/
      - run: mkdir test-reports
#      - run:
#          name: Download Selenium
#          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
#      - run:
#          name: Start Selenium
#          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
#          background: true

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
#      - run: cd web
#      - run: php -S localhost:8080
      # run tests!
      - run: vendor/bin/codecept run
